LIB_CPPFLAGS = @LIB_CPPFLAGS@
SETEGID = 
LIBDIR = ${libdir}
libdatadir = /usr/local/share/oposband/
vardatadir = /usr/local/var/games/oposband/
docdatadir = /usr/local/share/doc/oposband/
configdir = /usr/local/etc/oposband/
pdfdir ?= ${docdir}
ECHO_N ?= -n
bindir ?= /usr/local/games
dvidir ?= ${docdir}
datadir ?= ${datarootdir}
CPPFLAGS ?=  -I.
SHELL ?= /bin/sh
program_transform_name ?= s,x,x,
DEFS ?= -DHAVE_CONFIG_H
infodir ?= ${datarootdir}/info
libexecdir ?= ${exec_prefix}/libexec
localedir ?= ${datarootdir}/locale
LTLIBOBJS ?= 
LDFLAGS ?=  
includedir ?= ${prefix}/include
libdir ?= ${exec_prefix}/lib
localstatedir ?= ${prefix}/var
docdir ?= ${prefix}/share/doc/oposband
INSTALL_SCRIPT ?= ${INSTALL}
MV ?= /bin/mv
GLIB_LIBS ?= @GLIB_LIBS@
sharedstatedir ?= ${prefix}/com
GTK_CFLAGS ?= @GTK_CFLAGS@
OBJEXT ?= o
PKG_CONFIG ?= @PKG_CONFIG@
sysconfdir ?= ${prefix}/etc
htmldir ?= ${docdir}
PACKAGE_STRING ?= Oposband 0.1.1
sbindir ?= ${exec_prefix}/sbin
CP ?= /bin/cp
SET_MAKE ?= 
ECHO_C ?= 
psdir ?= ${docdir}
oldincludedir ?= /usr/include
GTK_LIBS ?= @GTK_LIBS@
mandir ?= ${datarootdir}/man
PACKAGE_NAME ?= Oposband
ECHO_T ?= 
LIBOBJS ?= 
ac_ct_CC ?= gcc
PACKAGE_VERSION ?= 0.1.1
LN_S ?= ln -s
GREP ?= /bin/grep
INSTALL_DATA ?= ${INSTALL} -m 644
datarootdir ?= ${prefix}/share
RM ?= /bin/rm
INSTALL_PROGRAM ?= ${INSTALL}
exec_prefix ?= /usr/local
EGREP ?= /bin/grep -E
prefix ?= /usr/local
RC ?= no
VERSION ?= @VERSION@
MAINFILES = $(BASEMAINFILES)
USE_STATS = 
DISTCLEAN = doc/manual/manual.pdf
